// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOQetgh91-gPDkqTAX7sg9teD7cWKbkgg',
    appId: '1:421248056209:web:a5968d2af807af6dce3830',
    messagingSenderId: '421248056209',
    projectId: 'voting-7873d',
    authDomain: 'voting-7873d.firebaseapp.com',
    storageBucket: 'voting-7873d.appspot.com',
    measurementId: 'G-W7XVLSRP3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvRaGZvNixTECkdza2QWhV9swngOVPPs',
    appId: '1:421248056209:android:0a27d2577f44027cce3830',
    messagingSenderId: '421248056209',
    projectId: 'voting-7873d',
    storageBucket: 'voting-7873d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBva18UE61_duOP4dZvqjhmywBmu7hqXyE',
    appId: '1:421248056209:ios:1128eb55d61e872cce3830',
    messagingSenderId: '421248056209',
    projectId: 'voting-7873d',
    storageBucket: 'voting-7873d.appspot.com',
    iosBundleId: 'com.mohammadareebkashaf.votingHandler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBva18UE61_duOP4dZvqjhmywBmu7hqXyE',
    appId: '1:421248056209:ios:1128eb55d61e872cce3830',
    messagingSenderId: '421248056209',
    projectId: 'voting-7873d',
    storageBucket: 'voting-7873d.appspot.com',
    iosBundleId: 'com.mohammadareebkashaf.votingHandler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOQetgh91-gPDkqTAX7sg9teD7cWKbkgg',
    appId: '1:421248056209:web:5c8dfe5c57bd4891ce3830',
    messagingSenderId: '421248056209',
    projectId: 'voting-7873d',
    authDomain: 'voting-7873d.firebaseapp.com',
    storageBucket: 'voting-7873d.appspot.com',
    measurementId: 'G-0479HF1D0X',
  );
}
